"""GitHub-flavored markdown renderer for ImpactResult.

Lives outside `commands/analyze.py` so the SaaS backend can import it cleanly
without pulling Click in. The CLI imports it back for the `--format markdown`
output path.
"""
from __future__ import annotations

from typing import Optional

from .change_impact import ImpactResult
from .relevance import format_match_narrative


SEVERITY_EMOJI = {
    "critical": ":red_circle:",
    "high": ":warning:",
    "medium": ":large_blue_circle:",
    "low": ":white_check_mark:",
}


def format_impact_markdown(result: ImpactResult, *, heading: Optional[str] = None) -> str:
    """Render an ImpactResult as a GitHub-flavored markdown PR comment.

    Args:
        result: The `analyze_change_impact` output.
        heading: Override the default "## Terraform Risk Analysis" heading.

    The output is scannable in under 20 seconds — title, score + severity,
    summary table, top 3 score drivers, top 3 contextual checks, top 3
    relevant past fixes, and any historical apply failures.
    """
    lines = []

    sev = result.severity.upper()
    emoji = SEVERITY_EMOJI.get(result.severity, "")

    lines.append(heading or "## Terraform Risk Analysis")
    lines.append("")
    lines.append(f"**Risk: {result.score:.0f}/100** {emoji} **{sev}**")
    lines.append("")

    ps = result.plan_summary
    by_action = ps.get("by_action", {})
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total changes | {ps.get('total_changes', 0)} |")
    lines.append(f"| Creates | {by_action.get('create', 0)} |")
    lines.append(f"| Updates | {by_action.get('update', 0)} |")
    lines.append(f"| Deletes | {by_action.get('delete', 0)} |")
    lines.append(f"| Replaces | {by_action.get('replace', 0)} |")
    lines.append(f"| Control points | {ps.get('control_points', 0)} |")
    lines.append(f"| Impacted resources | {ps.get('affected_resources', 0)} |")
    lines.append("")

    if result.score_explanation:
        visible = [e for e in result.score_explanation if e.get("kind") != "modifier"]
        visible.sort(key=lambda e: e.get("delta", 0), reverse=True)
        visible = visible[:3]
        if visible:
            lines.append("### Why this score?")
            for item in visible:
                delta = item.get("delta", 0)
                delta_str = f" (+{delta:.0f})" if delta > 0 else ""
                lines.append(f"- {item['label']}{delta_str}")
            lines.append("")

    ctx_checks = result.contextual_checks if result.contextual_checks else []
    if not ctx_checks and result.checks:
        ctx_checks = [
            {"check": c, "source": "category", "resource": ""} for c in result.checks
        ]
    if ctx_checks:
        lines.append("### Contextual Checks")
        for item in ctx_checks[:3]:
            source = item.get("source", "")
            check_text = item.get("check", "")
            lines.append(f"- **[{source}]** {check_text}")
        lines.append("")

    fixes = result.relevant_fixes if result.relevant_fixes else result.resource_warnings
    if fixes:
        lines.append("### Relevant Past Fixes")
        lines.append("")
        for f in fixes[:3]:
            short_id = f.get("short_id", "?")
            confidence = f.get("confidence", "low")
            similar = f.get("similar_count", 0)
            narrative = f.get("narrative") or format_match_narrative(f)
            resolution = f.get("resolution", "")
            res_disp = resolution[:100] + "..." if len(resolution) > 100 else resolution
            similar_str = f" [+{similar} similar]" if similar > 0 else ""
            lines.append(
                f"- **FIX-{short_id}** [{confidence}]{similar_str}: {narrative}"
            )
            lines.append(f"  - {res_disp}")
        lines.append("")

    if result.outcome_matches:
        lines.append("### Historical Apply Outcomes")
        lines.append("")
        for om in result.outcome_matches:
            applied = (om.get("applied_at") or "")[:10]
            err_codes = om.get("apply_error_codes", [])
            err_str = f" Error: {', '.join(err_codes)}" if err_codes else ""
            oid = om.get("outcome_id", "?")
            lines.append(
                f"- :rotating_light: This change pattern previously failed."
                f" Last failure: {applied}.{err_str} (Outcome: {oid})"
            )
        lines.append("")

    lines.append("---")
    lines.append("<sub>Generated by FixDoc</sub>")

    return "\n".join(lines)


# HTML marker used for idempotent PR comment updates. The GitHub App looks for
# this sentinel when deciding whether to post a new comment or update the
# existing one; keep it stable across backend and CLI renders so a repo that
# mixes the two paths doesn't end up with duplicated comments.
FIXDOC_COMMENT_MARKER = "<!-- fixdoc-risk-analysis -->"


def format_impact_pr_comment(result: ImpactResult) -> str:
    """Same as `format_impact_markdown` but prepends the idempotency marker."""
    return f"{FIXDOC_COMMENT_MARKER}\n{format_impact_markdown(result)}"
